repos:
# - repo: https://github.com/charliermarsh/ruff-pre-commit
#   # Ruff version.
#   rev: 'v0.1.0'
#   hooks:
#     - id: ruff
#       args: ['--fix', '--config', 'pyproject.toml']

- repo: https://github.com/psf/black
  rev: 'refs/tags/23.10.0:refs/tags/23.10.0'
  hooks:
    - id: black
      language_version: python3.10
      args: ['--config', 'pyproject.toml']
      verbose: true

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  -   id: end-of-file-fixer
      exclude: |
        (?x)(
          ^docs/
        )
  -   id: debug-statements # Ensure we don't commit `import pdb; pdb.set_trace()`
  -   id: trailing-whitespace
      exclude: |
        (?x)(
          ^docs/
        )
# - repo: https://github.com/pre-commit/mirrors-mypy
#   rev: v1.6.1
#   hooks:
#   -   id: mypy
