
# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: build

on:
  push:
    branches: [ master, future ]
  pull_request:


jobs:
  # Run tests on different versions of python
  unittest:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-22.04, macos-latest]
        # https://devguide.python.org/versions/
        python-version: ["3.10", "3.11", "3.12", "3.13"]
        exclude:
          - os: windows-latest
            python-version: "3.11"
          - os: windows-latest
            python-version: "3.12"

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[dev]
    - name: Test with pytest
      env:
        MPLBACKEND: Agg
      run: |
        pytest -s --timeout=50 --timeout_method=thread

  all-unittests-passed:
    needs: unittest
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Check unittest status
        if: ${{ needs.unittest.result != 'success' }}
        run: exit 1

  codecov:
    # If all tests pass:
    # Run coverage and upload to codecov
    needs: unittest
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[dev]
    - name: Run coverage
      run: |
        coverage run --omit='tests/*.py,tests/base/*.py' -m pytest
        coverage report
        coverage xml 
    - name: upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        file: ./coverage.xml
  sphinx:
    # If the above worked:
    # Build docs and upload to GH Pages
    needs: unittest
    uses: ./.github/workflows/sphinx.yml
